### ISSUE TITLE
[Feature Request] Saving the preset of custom paths

### ISSUE THREAD

**Issue by Shadowheg** [DjLeChuck/foundryvtt-babele-translation-files-generator#4]
Very often when using the module I use the same custom paths to retrieve many compendiums. I have to manually enter them in the module settings. It would be very convenient if you could save and load the preset of custom paths. Please consider implementing this feature. Or saving custom paths as a global setting in the module. Now when switching from one compendium to another, custom paths are reset.

**Comment by DjLeChuck** [comment]
Done with 12.1.0

I’ve add two buttons next to the one to add custom mapping: export and import.

The first saves the custom mapping in a JSON file, the second allow to import back the file to override the defined custom mapping.
